import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms & Conditions',
  description: 'Terms and Conditions governing the use of Vian Software Solutions website, services, software, platforms, and products.',
}

export default function TermsPage() {
  return (
    <>
      <section className="page-hero">
        <div className="container">
          <div className="breadcrumb">
            <a href="/">Home</a>
            <span>/</span>
            <span>Legal</span>
            <span>/</span>
            <span>Terms & Conditions</span>
          </div>
          <span className="eyebrow">Legal</span>
          <h1>Terms & Conditions</h1>
          <p className="lead">These Terms and Conditions govern your access to our website, services, software, platforms, and all products offered by Vian Software Solutions.</p>
          <p className="small muted" style={{ marginTop: 8 }}>Last updated: June 25, 2026</p>
        </div>
      </section>

      <section className="section">
        <div className="container">
          <div className="legal-wrapper">
            <aside className="legal-sidebar">
              <h4>Contents</h4>
              <a href="#acceptance">1. Acceptance of Terms</a>
              <a href="#definitions">2. Definitions</a>
              <a href="#eligibility">3. Eligibility</a>
              <a href="#services">4. Services Offered</a>
              <a href="#quotation">5. Quotation & Project Acceptance</a>
              <a href="#fees">6. Fees, Payments & Taxes</a>
              <a href="#invoicing">7. Invoicing & Payment Terms</a>
              <a href="#timelines">8. Project Timelines & Milestones</a>
              <a href="#client-responsibilities">9. Client Responsibilities</a>
              <a href="#communication">10. Communication & Reporting</a>
              <a href="#change-orders">11. Scope Changes & Change Orders</a>
              <a href="#revisions">12. Revisions & Acceptance</a>
              <a href="#ip">13. Intellectual Property Rights</a>
              <a href="#confidentiality">14. Confidentiality</a>
              <a href="#licensing">15. Software Licensing & Usage Rights</a>
              <a href="#third-party">16. Third-Party Services & Dependencies</a>
              <a href="#support">17. Support & Maintenance Terms</a>
              <a href="#account">18. Account Registration & Security</a>
              <a href="#aup">19. Acceptable Use Policy</a>
              <a href="#termination">20. Termination & Suspension</a>
              <a href="#force-majeure">21. Force Majeure</a>
              <a href="#disclaimer">22. Disclaimer of Warranties</a>
              <a href="#liability">23. Limitation of Liability</a>
              <a href="#indemnification">24. Indemnification</a>
              <a href="#governing-law">25. Governing Law</a>
              <a href="#dispute-resolution">26. Dispute Resolution</a>
              <a href="#modifications">27. Modifications to Terms</a>
              <a href="#entire-agreement">28. Entire Agreement</a>
              <a href="#severability">29. Severability</a>
              <a href="#waiver">30. Waiver</a>
              <a href="#assignment">31. Assignment</a>
              <a href="#notices">32. Notices</a>
              <a href="#contact">33. Contact Information</a>
            </aside>
            <div className="legal-doc">
              <h2 id="acceptance">1. Acceptance of Terms</h2>
              <p>By accessing, browsing, or using the website of Vian Software Solutions (hereinafter referred to as "the Company," "we," "us," or "our"), or by engaging our services, submitting a quotation request, executing a Statement of Work, or making any payment to us, you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions (the "Terms"). If you do not agree to these Terms in their entirety, you must immediately discontinue use of our website and refrain from engaging our services.</p>
              <p>These Terms constitute a legally binding agreement between you ("you," "Client," "User," or "Customer") and Vian Software Solutions, a Sole Proprietorship of Viren Pandey, registered under the laws of the Republic of India, with its principal place of business in Mumbai, Maharashtra, India. These Terms apply to all visitors, users, clients, and any other person or entity accessing or using our website, services, software, platforms, or digital products.</p>
              <p>These Terms incorporate by reference our <a href="/legal/privacy-policy">Privacy Policy</a> and <a href="/legal/refund-policy">Refund & Cancellation Policy</a>. By accepting these Terms, you also accept the terms of those policies. In the event of any conflict between these Terms and any other document, these Terms shall prevail unless expressly agreed otherwise in writing by both parties.</p>
              <p>We reserve the right to update or modify these Terms at any time without prior notice. Your continued use of our services after any such changes constitutes your acceptance of the new Terms. It is your responsibility to review these Terms periodically. The date of the most recent revision is indicated at the top of this page.</p>

              <h2 id="definitions">2. Definitions</h2>
              <p>For the purposes of these Terms, the following terms shall have the meanings ascribed to them below, unless the context otherwise requires:</p>
              <p><strong>"Agreement"</strong> means the collective contractual relationship between the Client and Vian Software Solutions, comprising these Terms, the applicable Statement of Work or quotation, and any exhibits, schedules, or appendices attached thereto.</p>
              <p><strong>"Client"</strong> or <strong>"Customer"</strong> means the individual, company, partnership, trust, association, or any other legal entity that engages Vian Software Solutions for services, purchases products, or accesses the website.</p>
              <p><strong>"Company"</strong>, <strong>"We"</strong>, <strong>"Us"</strong>, or <strong>"Our"</strong> means Vian Software Solutions, a Sole Proprietorship of Viren Pandey, having its registered address in Mumbai, Maharashtra, India.</p>
              <p><strong>"Confidential Information"</strong> means any and all information disclosed by one party to the other, whether orally, in writing, or in any other form, that is designated as confidential or that reasonably ought to be considered confidential given the nature of the information and the circumstances of disclosure, including but not limited to business plans, financial data, source code, algorithms, technical specifications, trade secrets, client lists, project requirements, system architectures, and any proprietary information.</p>
              <p><strong>"Deliverables"</strong> means the work product, software, code, designs, documentation, applications, platforms, or any other output that Vian Software Solutions is obligated to produce and deliver to the Client under a specific Statement of Work or quotation.</p>
              <p><strong>"Digital Products"</strong> means pre-built software solutions, templates, components, modules, libraries, or any other digital assets offered by the Company for license or sale, which may be delivered in a standard or configurable form.</p>
              <p><strong>"Effective Date"</strong> means the date on which the Client accepts a quotation or Statement of Work, or the date on which the Client first uses our services or website, whichever is earlier.</p>
              <p><strong>"Fees"</strong> means all charges, costs, and expenses payable by the Client to Vian Software Solutions as set forth in a quotation, Statement of Work, or invoice.</p>
              <p><strong>"Force Majeure Event"</strong> means any event or circumstance beyond the reasonable control of a party, including but not limited to acts of God, war, terrorism, civil unrest, pandemic, epidemic, government action or regulation, natural disasters, fire, flood, earthquake, prolonged power outages, internet service disruptions, cyber-attacks, labor disputes, and supply chain interruptions.</p>
              <p><strong>"Intellectual Property Rights"</strong> or <strong>"IPR"</strong> means all intellectual property rights of any kind whatsoever, whether registered or unregistered, including but not limited to copyrights, trademarks, service marks, trade names, trade secrets, patents, design rights, database rights, domain names, moral rights, and all other proprietary rights, together with any applications, renewals, extensions, and reissues thereof.</p>
              <p><strong>"Milestone"</strong> means a predefined stage or phase of a project as set forth in the quotation or Statement of Work, the completion of which triggers an invoicing and payment obligation.</p>
              <p><strong>"Parties"</strong> means Vian Software Solutions and the Client collectively. <strong>"Party"</strong> means either one of them individually.</p>
              <p><strong>"Pre-existing Materials"</strong> means all Intellectual Property, tools, libraries, frameworks, code snippets, methodologies, templates, know-how, and proprietary technologies owned or developed by Vian Software Solutions prior to the engagement, or developed independently of the Client's project, whether or not used in the course of performing services for the Client.</p>
              <p><strong>"Project"</strong> means the specific scope of work, development, or consulting engagement described in a quotation or Statement of Work accepted by the Client.</p>
              <p><strong>"Quotation"</strong> means a formal written estimate or proposal provided by Vian Software Solutions to a prospective Client, detailing the scope of work, deliverables, timelines, and fees for a specific project.</p>
              <p><strong>"Services"</strong> means all software development, consulting, design, technical, and professional services provided by Vian Software Solutions to the Client, as more particularly described in these Terms and in the applicable Statement of Work or quotation.</p>
              <p><strong>"Statement of Work"</strong> or <strong>"SOW"</strong> means a written document executed by both parties that describes the specific services, deliverables, timelines, fees, and other terms applicable to a particular engagement or project.</p>
              <p><strong>"Website"</strong> means the Company's website accessible at the domains operated by Vian Software Solutions, including all subdomains, pages, features, and content.</p>
              <p><strong>"Work Product"</strong> means all tangible and intangible output created by Vian Software Solutions for the Client under a project, including but not limited to source code, object code, documentation, designs, wireframes, databases, configurations, algorithms, and technical specifications.</p>

              <h2 id="eligibility">3. Eligibility & User Representations</h2>
              <p>By accepting these Terms and using our Services, you represent, warrant, and covenant that:</p>
              <p><strong>Legal Capacity:</strong> You are at least 18 years of age and possess the legal authority, capacity, and right to enter into these Terms and to perform your obligations hereunder. If you are entering into these Terms on behalf of a company, partnership, or other legal entity, you represent and warrant that you have the authority to bind such entity to these Terms.</p>
              <p><strong>Accuracy of Information:</strong> All information provided by you to Vian Software Solutions, including but not limited to personal details, business information, project requirements, billing information, and contact details, is accurate, complete, and current. You agree to update such information promptly in the event of any changes.</p>
              <p><strong>Compliance with Laws:</strong> You agree to comply with all applicable local, state, national, and international laws, regulations, and ordinances in connection with your use of our Services and Website. You shall not use our Services for any unlawful, fraudulent, or prohibited purpose.</p>
              <p><strong>No Conflict:</strong> You represent that your engagement of Vian Software Solutions does not violate any agreement, obligation, or duty you owe to any third party, including but not limited to any employment agreement, non-disclosure agreement, or non-compete agreement.</p>
              <p><strong>Financial Capacity:</strong> You represent that you have the financial capacity to pay all Fees as they become due under these Terms and any applicable SOW or quotation.</p>
              <p><strong>Business Purpose:</strong> You acknowledge that our Services are intended for business and commercial purposes and not for consumer or personal use, unless explicitly agreed otherwise in writing.</p>

              <h2 id="services">4. Services Offered</h2>
              <p>Vian Software Solutions offers a comprehensive range of technology services. Each service engagement is governed by a specific quotation or Statement of Work that defines the scope, deliverables, timelines, and fees. The following is a non-exhaustive list of the services we provide:</p>
              <p><strong>4.1 Custom Software Development:</strong> Design, development, testing, and deployment of bespoke software applications tailored to the Client's specific business requirements. This includes requirements analysis, system architecture design, coding, quality assurance, deployment, and documentation. Each custom software project is unique and is priced based on the specific requirements outlined in the quotation process.</p>
              <p><strong>4.2 Web Development:</strong> Development of websites, web portals, content management systems, e-commerce platforms, and web-based applications using modern frameworks and technologies. Services include front-end development, back-end development, database design, API integration, and responsive design implementation.</p>
              <p><strong>4.3 Mobile Application Development:</strong> Design and development of native and cross-platform mobile applications for iOS and Android platforms. Services include UI/UX design, app architecture, development, testing, app store submission, and ongoing maintenance.</p>
              <p><strong>4.4 Software as a Service (SaaS) Development:</strong> Development of cloud-based software platforms and SaaS products, including multi-tenant architecture, subscription management, payment gateway integration, user authentication, and scalable cloud infrastructure deployment.</p>
              <p><strong>4.5 Artificial Intelligence & Machine Learning:</strong> Development of AI/ML solutions including predictive models, natural language processing systems, computer vision applications, recommendation engines, chatbots, intelligent automation, and data analytics platforms.</p>
              <p><strong>4.6 Automation Services:</strong> Business process automation, robotic process automation (RPA), workflow automation, data pipeline automation, and integration of automated systems to improve operational efficiency.</p>
              <p><strong>4.7 API Development & Integration:</strong> Design, development, and documentation of RESTful and GraphQL APIs, third-party API integrations, system-to-system integration, and middleware development for seamless data exchange between platforms.</p>
              <p><strong>4.8 Cloud Services:</strong> Cloud architecture design, migration, deployment, and management on major cloud platforms including AWS, Google Cloud, Microsoft Azure, and other providers. Services include infrastructure-as-code implementation, containerization, serverless computing, and cloud optimization.</p>
              <p><strong>4.9 User Experience (UX) & Interface Design:</strong> User research, information architecture, wireframing, prototyping, visual design, and usability testing for web and mobile applications. Deliverables include design systems, style guides, and interactive prototypes.</p>
              <p><strong>4.10 Technology Consulting:</strong> Strategic technology advisory services including technology stack selection, digital transformation strategy, architecture review, technical due diligence, code audits, and technology roadmap planning.</p>
              <p><strong>4.11 Enterprise Software Solutions:</strong> Development of enterprise-grade software including ERP systems, CRM platforms, project management tools, inventory management systems, HR management systems, and other enterprise applications tailored to organizational needs.</p>
              <p><strong>4.12 Digital Products:</strong> Pre-built software solutions, components, templates, modules, libraries, and other digital assets offered under license. These products are provided "as-is" unless accompanied by a separate customization agreement.</p>
              <p>Each service engagement is initiated through our quotation process. The specific scope, deliverables, timelines, and pricing for any engagement shall be as set forth in the applicable quotation or Statement of Work. Vian Software Solutions reserves the right to refuse or decline any project request at its sole discretion.</p>

              <h2 id="quotation">5. Quotation Process & Project Acceptance</h2>
              <p>Vian Software Solutions operates on a quotation-based engagement model. The following process governs how projects are quoted, accepted, and commenced:</p>
              <p><strong>5.1 Initial Inquiry:</strong> A prospective Client may submit a project inquiry through our website, email, or other communication channels. The inquiry should include a description of the project requirements, desired timelines, budget parameters, and any relevant background information.</p>
              <p><strong>5.2 Requirements Analysis:</strong> Upon receiving an inquiry, Vian Software Solutions may conduct a preliminary analysis of the requirements. This may include discovery calls, written correspondence, review of existing systems, and clarification of project scope. We may request additional information from the Client to accurately assess the project requirements.</p>
              <p><strong>5.3 Preparation of Quotation:</strong> Based on the requirements analysis, Vian Software Solutions will prepare a formal written quotation (the "Quotation") addressed to the Client. The Quotation will typically include: (a) a description of the scope of work and deliverables; (b) the proposed project timeline and milestones; (c) the total estimated Fees and payment schedule; (d) assumptions, exclusions, and dependencies; and (e) the validity period of the Quotation.</p>
              <p><strong>5.4 Quotation Validity:</strong> Each Quotation shall be valid for the period stated therein, which is typically 15 to 30 days from the date of issuance. After the expiry of the validity period, Vian Software Solutions reserves the right to revise the Quotation, including pricing and timelines, at its sole discretion. No Quotation shall be binding until accepted in writing by the Client within the validity period.</p>
              <p><strong>5.5 Acceptance of Quotation:</strong> The Client may accept a Quotation by signing and returning the Quotation document, issuing a purchase order, accepting via email, providing written confirmation, or making an advance payment as specified in the Quotation. Upon acceptance, the Quotation becomes a binding contractual document between the parties, and the project shall be deemed to have commenced.</p>
              <p><strong>5.6 Statement of Work:</strong> For larger or more complex engagements, Vian Software Solutions may issue a Statement of Work (SOW) in addition to or in lieu of a Quotation. The SOW shall contain detailed specifications of the work to be performed and shall be signed by both parties. In the event of any inconsistency between these Terms and an SOW, the SOW shall prevail with respect to that specific project.</p>
              <p><strong>5.7 Pre-Engagement Checks:</strong> Vian Software Solutions reserves the right to conduct reasonable due diligence on prospective Clients, including verifying identity, business registration, and financial standing. We may decline to proceed with any engagement at our sole discretion based on the outcome of such checks.</p>
              <p><strong>5.8 No Obligation Until Acceptance:</strong> Neither party shall be under any obligation to proceed with a project until a Quotation or SOW has been accepted in accordance with this section. Any work performed by Vian Software Solutions prior to formal acceptance shall be at the Company's own risk and shall not obligate the Client to pay for such work unless expressly agreed in writing.</p>

              <h2 id="fees">6. Fees, Payments & Taxes</h2>
              <p><strong>6.1 Fee Structure:</strong> All Fees for Services shall be as set forth in the applicable Quotation or SOW. Fees may be structured as: (a) fixed-price project fees; (b) time and materials based on hourly or daily rates; (c) milestone-based payments; (d) retainer-based monthly fees; (e) subscription fees for SaaS or maintenance services; or (f) any combination of the foregoing, as agreed in writing.</p>
              <p><strong>6.2 Changes to Fees:</strong> Vian Software Solutions reserves the right to revise its standard rates and fee schedules from time to time. However, for any accepted Quotation or SOW, the Fees shall remain fixed as stated therein, unless the scope of work changes pursuant to the Change Order process described in Section 11.</p>
              <p><strong>6.3 Taxes:</strong> All Fees are exclusive of all applicable taxes, duties, levies, and government charges. The Client shall be responsible for paying all taxes imposed by any government authority in connection with the Services, including but not limited to Goods and Services Tax (GST), value-added tax (VAT), service tax, withholding tax, and any other similar charges. If Vian Software Solutions is required to collect or remit any taxes, such taxes shall be added to the Fees and invoiced to the Client.</p>
              <p><strong>6.4 Withholding Tax:</strong> If the Client is required by applicable law to deduct withholding tax from any payment due to Vian Software Solutions, the Client shall gross up the payment such that the net amount received by Vian Software Solutions equals the full invoiced amount. The Client shall provide Vian Software Solutions with official tax receipts or certificates evidencing the withholding within 30 days of making the deduction.</p>
              <p><strong>6.5 Currency:</strong> All Fees are quoted and payable in Indian Rupees (INR) unless otherwise agreed in writing. If payment is made in a foreign currency, the exchange rate applicable on the date of payment shall be used, and the Client shall bear all currency conversion charges and bank fees.</p>
              <p><strong>6.6 Payment Methods:</strong> We accept payments through bank transfers, UPI, credit/debit cards, and other electronic payment methods as may be specified on invoices or through our payment gateway. The Client shall bear any transaction fees, processing charges, or gateway fees associated with the chosen payment method.</p>
              <p><strong>6.7 Late Payment:</strong> If the Client fails to make any payment when due, Vian Software Solutions reserves the right to: (a) charge interest on the overdue amount at the rate of 1.5% per month (18% per annum) or the maximum permitted by law, whichever is lower, compounded monthly from the due date until the date of full payment; (b) suspend all Services and work on all projects until all outstanding amounts are paid in full; (c) withhold delivery of any Deliverables, source code, or work product; and (d) pursue any other remedies available under these Terms or applicable law.</p>
              <p><strong>6.8 Disputed Amounts:</strong> If the Client disputes any portion of an invoice in good faith, the Client shall notify Vian Software Solutions in writing within 5 business days of receipt of the invoice, specifying the nature and amount of the dispute. The parties shall work in good faith to resolve the dispute promptly. The Client shall pay all undisputed portions of the invoice on or before the due date. No withholding of payment for disputed amounts shall constitute a breach of these Terms, provided the dispute is raised in good faith and the Client continues to pay all undisputed amounts.</p>
              <p><strong>6.9 Recovery Costs:</strong> In the event Vian Software Solutions engages a collection agency or takes legal action to recover unpaid Fees, the Client shall be liable for all reasonable collection costs, legal fees, and court costs incurred by Vian Software Solutions.</p>

              <h2 id="invoicing">7. Invoicing & Payment Terms</h2>
              <p><strong>7.1 Invoicing Schedule:</strong> Vian Software Solutions shall issue invoices in accordance with the payment schedule set forth in the applicable Quotation or SOW. In the absence of a specified schedule, invoices shall be issued as follows: (a) an advance invoice upon acceptance of the Quotation or SOW; (b) subsequent invoices upon completion of each Milestone; and (c) a final invoice upon completion and delivery of all Deliverables.</p>
              <p><strong>7.2 Payment Terms:</strong> Unless otherwise agreed in writing, all invoices are due and payable within 15 calendar days from the date of invoice. For retainer or subscription-based services, payment is due in advance before the commencement of the billing period.</p>
              <p><strong>7.3 Advance Payments:</strong> For new Clients or projects exceeding a certain threshold (as determined by Vian Software Solutions in its discretion), we may require an advance payment of 30% to 50% of the total project Fees before work commences. This advance payment is non-refundable as per our <a href="/legal/refund-policy">Refund & Cancellation Policy</a>.</p>
              <p><strong>7.4 Milestone Payments:</strong> For milestone-based projects, each Milestone shall be invoiced upon the earlier of: (a) completion of the Milestone and delivery of the corresponding Deliverable to the Client; or (b) the scheduled Milestone date as set forth in the project timeline. Milestone payments are non-refundable once the Milestone is completed and delivered.</p>
              <p><strong>7.5 Electronic Invoices:</strong> All invoices shall be delivered electronically to the Client's registered email address. The Client is responsible for ensuring that their billing contact information is accurate and current. Invoices are deemed received 24 hours after sending.</p>
              <p><strong>7.6 Payment Receipts:</strong> Upon receipt of payment, Vian Software Solutions shall issue a payment receipt or tax invoice, as applicable, in compliance with Indian tax laws and regulations.</p>
              <p><strong>7.7 Set-Off:</strong> The Client shall not be entitled to set off, withhold, or deduct any amounts due to Vian Software Solutions against any alleged claims, counterclaims, or disputes, unless expressly agreed in writing by Vian Software Solutions or required by applicable law.</p>

              <h2 id="timelines">8. Project Timelines & Milestones</h2>
              <p><strong>8.1 Estimated Timelines:</strong> All project timelines and milestone dates provided in Quotations or SOWs are estimates made in good faith based on the information available at the time. Vian Software Solutions shall use reasonable commercial efforts to meet the estimated timelines but does not guarantee strict adherence to them.</p>
              <p><strong>8.2 Dependency on Client Input:</strong> Project timelines are inherently dependent on the timely provision of Client inputs, feedback, approvals, and decisions. Any delay by the Client in providing required inputs, feedback, or approvals shall result in a corresponding extension of the project timeline, and Vian Software Solutions shall not be liable for such delays.</p>
              <p><strong>8.3 Notification of Delays:</strong> If Vian Software Solutions becomes aware of any anticipated delay in meeting a Milestone or delivery date, we shall promptly notify the Client in writing, providing an updated timeline and the reason for the delay.</p>
              <p><strong>8.4 No Liquidated Damages:</strong> Unless expressly agreed otherwise in writing, Vian Software Solutions shall not be liable for any delay in project completion, and the Client shall not be entitled to any liquidated damages, penalty, or fee reduction as a result of such delay.</p>
              <p><strong>8.5 Early Completion:</strong> Vian Software Solutions reserves the right to complete projects or milestones ahead of the estimated timeline. Early completion shall not entitle the Client to any fee reduction or adjustment.</p>
              <p><strong>8.6 Timeline Revisions:</strong> The parties may mutually agree to revise project timelines in writing. Any such revision shall be documented and acknowledged by both parties. Scope changes pursuant to Section 11 may also result in timeline adjustments.</p>
              <p><strong>8.7 Suspension of Timeline:</strong> If the Client fails to make a payment when due, fails to provide required inputs or feedback for more than 10 business days, or otherwise breaches these Terms, the project timeline shall be suspended until the breach is cured. Vian Software Solutions shall not be liable for any consequences arising from such suspension.</p>

              <h2 id="client-responsibilities">9. Client Responsibilities</h2>
              <p>The Client acknowledges and agrees to the following responsibilities, which are essential to the successful execution of any project:</p>
              <p><strong>9.1 Provision of Information:</strong> The Client shall provide Vian Software Solutions with timely, accurate, and complete information, materials, and documentation reasonably required for the performance of Services. This includes project requirements, technical specifications, design preferences, access credentials, content, data, and any other materials necessary for the project.</p>
              <p><strong>9.2 Access and Cooperation:</strong> The Client shall provide Vian Software Solutions with reasonable access to the Client's personnel, systems, servers, data, and facilities as required for the performance of Services. The Client shall designate a single point of contact who is authorized to make decisions and provide approvals on behalf of the Client.</p>
              <p><strong>9.3 Timely Feedback and Approvals:</strong> The Client shall review deliverables, provide feedback, and grant approvals within the timeframes specified in the project timeline or, if no timeframe is specified, within 5 business days of receipt. Failure to provide timely feedback may result in project delays and additional charges.</p>
              <p><strong>9.4 Third-Party Accounts and Credentials:</strong> The Client shall obtain, maintain, and provide all necessary third-party accounts, subscriptions, licenses, API keys, and credentials required for the project. The Client shall ensure that it has the legal right to use any third-party services, content, or materials provided to Vian Software Solutions.</p>
              <p><strong>9.5 Compliance with Laws:</strong> The Client shall ensure that its use of the Services and Deliverables complies with all applicable laws, regulations, and industry standards. The Client shall not use the Deliverables for any unlawful, harmful, or prohibited purpose.</p>
              <p><strong>9.6 Testing and Acceptance:</strong> The Client is responsible for conducting thorough testing of all Deliverables to ensure they meet the specified requirements before providing final acceptance. Vian Software Solutions shall provide reasonable support during the testing phase.</p>
              <p><strong>9.7 Security and Confidentiality:</strong> The Client shall implement reasonable security measures to protect any Confidential Information, credentials, and access provided by Vian Software Solutions. The Client shall immediately notify Vian Software Solutions of any security breach or unauthorized access.</p>
              <p><strong>9.8 No Unauthorized Modifications:</strong> The Client shall not modify, reverse engineer, decompile, or disassemble any Deliverables without the prior written consent of Vian Software Solutions, except as expressly permitted under these Terms or applicable law.</p>
              <p><strong>9.9 Client Systems and Infrastructure:</strong> The Client is responsible for ensuring that its systems, hardware, software, and network infrastructure meet the technical requirements for the proper functioning of the Deliverables. Vian Software Solutions shall not be liable for issues arising from inadequate Client infrastructure.</p>

              <h2 id="communication">10. Communication & Reporting</h2>
              <p><strong>10.1 Primary Communication Channels:</strong> All formal communications between the parties shall be conducted through email, project management tools, or other written channels as agreed upon. Email communications to the designated contact addresses shall constitute valid written notice for all purposes under these Terms.</p>
              <p><strong>10.2 Designated Contacts:</strong> Each party shall designate one or more individuals as the primary point(s) of contact for the project. All significant communications, decisions, and approvals shall be routed through the designated contacts.</p>
              <p><strong>10.3 Progress Reporting:</strong> Unless otherwise agreed in the SOW, Vian Software Solutions shall provide periodic progress reports to the Client at intervals specified in the project plan, typically weekly or bi-weekly. Reports shall include: (a) work completed during the reporting period; (b) work planned for the next period; (c) any issues, risks, or blockers; and (d) updated timeline projections if applicable.</p>
              <p><strong>10.4 Status Meetings:</strong> Vian Software Solutions may schedule regular status meetings with the Client to review progress, discuss issues, and align on next steps. Meeting frequency and format shall be mutually agreed upon.</p>
              <p><strong>10.5 Response Times:</strong> Vian Software Solutions shall use reasonable efforts to respond to Client communications within 24 business hours during regular business days. Responses may take longer on weekends, public holidays, or during scheduled leave periods, of which the Client shall be notified in advance where reasonably practicable.</p>
              <p><strong>10.6 Project Documentation:</strong> Vian Software Solutions shall maintain reasonable documentation of project decisions, requirements, and changes. Such documentation may be shared with the Client upon request.</p>
              <p><strong>10.7 Emergency Communications:</strong> In the event of a critical issue or security incident affecting the Client's project or data, Vian Software Solutions shall notify the Client as promptly as reasonably practicable using the most expedient communication method available.</p>

              <h2 id="change-orders">11. Scope Changes & Change Orders</h2>
              <p><strong>11.1 Scope Definition:</strong> The scope of work for each project is defined in the applicable Quotation or SOW. Any changes, additions, or modifications to the scope shall be governed by this Section 11.</p>
              <p><strong>11.2 Change Requests:</strong> Either party may propose a change to the project scope, deliverables, timeline, or Fees by submitting a written change request (a "Change Request") to the other party. The Change Request shall describe the proposed change in sufficient detail to allow the other party to assess its impact.</p>
              <p><strong>11.3 Change Order Process:</strong> Upon receipt of a Change Request, Vian Software Solutions shall assess the impact of the proposed change on the project timeline, Fees, resources, and other terms. Vian Software Solutions shall provide the Client with a written change order (a "Change Order") specifying: (a) the description of the proposed change; (b) the impact on project timeline; (c) any adjustment to Fees; (d) any other changes to the terms of the engagement; and (e) the validity period of the Change Order.</p>
              <p><strong>11.4 Approval of Change Orders:</strong> A Change Order shall become effective only upon written acceptance by the Client. Vian Software Solutions shall not be obligated to commence work on any scope change until the corresponding Change Order is accepted and, if applicable, any additional Fees are paid or secured.</p>
              <p><strong>11.5 Minor Changes:</strong> Minor changes that do not materially affect the scope, timeline, or Fees may be implemented without a formal Change Order, provided they are documented in writing (including via email) and agreed upon by both parties' designated contacts.</p>
              <p><strong>11.6 No Obligation to Accept:</strong> Neither party shall be obligated to accept a Change Request. If the parties cannot agree on the terms of a Change Order, the project shall continue in accordance with the original scope and terms.</p>
              <p><strong>11.7 Unauthorized Work:</strong> Any work performed by Vian Software Solutions at the Client's request that is outside the defined scope and not covered by a duly accepted Change Order shall be billed at Vian Software Solutions' then-current standard rates, and the Client shall be obligated to pay for such work.</p>

              <h2 id="revisions">12. Revisions & Acceptance</h2>
              <p><strong>12.1 Revision Cycles:</strong> The number of revision cycles included in the project Fees shall be specified in the Quotation or SOW. Unless otherwise stated, standard projects include up to two (2) revision cycles for each Deliverable. Additional revision cycles beyond the included amount shall be billed at Vian Software Solutions' then-current hourly rates.</p>
              <p><strong>12.2 Revision Scope:</strong> Revisions shall be limited to the refinement and improvement of the existing Deliverable and shall not constitute a change in scope. Any revision request that materially alters the original requirements shall be treated as a scope change under Section 11.</p>
              <p><strong>12.3 Submission of Revisions:</strong> The Client shall submit all revision requests in writing, consolidating all comments and change requests for each revision cycle into a single communication. Revision requests that are vague, incomplete, or contradictory may be returned to the Client for clarification.</p>
              <p><strong>12.4 Acceptance Procedure:</strong> Upon delivery of a Deliverable, the Client shall have a review period of 5 business days (or as specified in the SOW) to either: (a) provide written acceptance of the Deliverable; or (b) provide written notice of rejection with detailed reasons. If the Client fails to provide either acceptance or rejection within the review period, the Deliverable shall be deemed accepted.</p>
              <p><strong>12.5 Final Acceptance:</strong> Final acceptance of a Deliverable occurs when: (a) the Client provides written acceptance; (b) the Deliverable is deemed accepted under Section 12.4; (c) the Client makes any use of the Deliverable in a production or live environment; or (d) the Client makes any payment related to the Deliverable after delivery, whichever occurs first.</p>
              <p><strong>12.6 Effect of Acceptance:</strong> Upon final acceptance of a Deliverable: (a) all associated Fees become immediately due and payable; (b) the Deliverable is deemed to meet the requirements as specified; and (c) any warranty obligations with respect to that Deliverable commence as provided in these Terms.</p>

              <h2 id="ip">13. Intellectual Property Rights</h2>
              <p><strong>13.1 Ownership of Work Product:</strong> Upon full and final payment of all Fees due under the applicable Quotation or SOW, Vian Software Solutions hereby assigns and transfers to the Client all right, title, and interest in and to the Work Product specifically developed for the Client under that project. This assignment includes all Intellectual Property Rights in the Work Product, subject to the limitations set forth in this Section 13.</p>
              <p><strong>13.2 Pre-existing Materials:</strong> All Pre-existing Materials owned or developed by Vian Software Solutions prior to the engagement, or developed independently of the Client's project, shall remain the sole and exclusive property of Vian Software Solutions. This includes but is not limited to: (a) internal frameworks, libraries, and code snippets; (b) proprietary algorithms and methodologies; (c) development tools and utilities; (d) templates and boilerplate code; (e) know-how and technical expertise; and (f) any modifications, improvements, or derivatives thereof made during the project. Vian Software Solutions retains all Intellectual Property Rights in its Pre-existing Materials.</p>
              <p><strong>13.3 License to Pre-existing Materials:</strong> To the extent any Pre-existing Materials of Vian Software Solutions are incorporated into the Work Product, Vian Software Solutions hereby grants the Client a perpetual, worldwide, non-exclusive, royalty-free, fully paid-up, non-transferable license to use such Pre-existing Materials solely as part of and integrated with the Work Product. The Client shall not extract, copy, or use the Pre-existing Materials separately from the Work Product, except as expressly permitted by Vian Software Solutions in writing.</p>
              <p><strong>13.4 Third-Party Code and Open Source Components:</strong> The Work Product may incorporate third-party code, open-source components, libraries, or frameworks that are licensed under their respective open-source licenses (e.g., MIT, Apache 2.0, GPL, BSD). Such components remain under their original licenses and are not assigned to the Client. Vian Software Solutions shall use commercially reasonable efforts to: (a) identify third-party components included in the Work Product; (b) select components with licenses compatible with the intended use; and (c) comply with all applicable open-source license requirements. The Client is responsible for ensuring compliance with the terms of all third-party licenses applicable to their use of the Deliverables.</p>
              <p><strong>13.5 Client Materials:</strong> All materials, content, data, and Intellectual Property provided by the Client to Vian Software Solutions remain the sole property of the Client. The Client grants Vian Software Solutions a limited, non-exclusive, royalty-free license to use, reproduce, modify, and display such Client materials solely for the purpose of performing the Services under the applicable engagement. This license terminates upon completion of the Services, except to the extent necessary to maintain or support the Deliverables.</p>
              <p><strong>13.6 Moral Rights:</strong> To the maximum extent permitted by applicable law, the Client agrees not to assert any moral rights, droit moral, or similar rights against Vian Software Solutions in connection with the Work Product. If such rights cannot be waived, the Client agrees not to enforce them in a manner that would restrict Vian Software Solutions' ability to use its Pre-existing Materials or general expertise in future projects.</p>
              <p><strong>13.7 Residual Rights:</strong> Vian Software Solutions retains the right to use the general knowledge, skills, experience, and expertise gained through performing Services for the Client, provided that such use does not disclose the Client's Confidential Information or infringe the Client's Intellectual Property Rights.</p>
              <p><strong>13.8 Portfolio and Attribution:</strong> Vian Software Solutions reserves the right to: (a) display screenshots, descriptions, and case studies of the Work Product in its portfolio, website, and marketing materials; and (b) attribute the work to Vian Software Solutions, including links and credits. The Client may opt out of such attribution by providing written notice at the time of engagement. Vian Software Solutions shall not display any Confidential Information or sensitive data without the Client's prior written consent.</p>
              <p><strong>13.9 Non-Exclusivity:</strong> Unless expressly agreed otherwise in writing, the engagement of Vian Software Solutions is non-exclusive, and Vian Software Solutions reserves the right to provide similar services to other clients, including competitors of the Client, using the same Pre-existing Materials and general expertise, provided that no Confidential Information of the Client is disclosed.</p>
              <p><strong>13.10 Copyright Registration:</strong> Upon the Client's request and at the Client's expense, Vian Software Solutions shall provide reasonable assistance with the registration of copyrights, patents, or other Intellectual Property protection for the Work Product, to the extent such assistance is reasonably available.</p>

              <h2 id="confidentiality">14. Confidentiality</h2>
              <p><strong>14.1 Obligation of Confidentiality:</strong> Each party (the "Receiving Party") agrees to hold in strict confidence and not to disclose to any third party any Confidential Information of the other party (the "Disclosing Party"). The Receiving Party shall use the Confidential Information solely for the purpose of performing its obligations or exercising its rights under these Terms and the applicable engagement.</p>
              <p><strong>14.2 Standard of Care:</strong> The Receiving Party shall protect the Confidential Information of the Disclosing Party using the same degree of care that it uses to protect its own confidential information of a similar nature, but in no event less than reasonable care. The Receiving Party shall implement and maintain appropriate technical, physical, and organizational security measures to prevent unauthorized access, use, disclosure, or loss of Confidential Information.</p>
              <p><strong>14.3 Permitted Disclosures:</strong> The Receiving Party may disclose Confidential Information to: (a) its employees, contractors, and agents who have a need to know and are bound by confidentiality obligations at least as restrictive as those contained herein; (b) its legal and financial advisors bound by professional confidentiality obligations; (c) as required by applicable law, regulation, or court order, provided that the Receiving Party gives the Disclosing Party prompt notice (to the extent legally permitted) and cooperates in seeking a protective order or other appropriate relief; and (d) in connection with the enforcement of rights under these Terms.</p>
              <p><strong>14.4 Exclusions:</strong> Confidential Information does not include information that: (a) is or becomes publicly known through no fault of the Receiving Party; (b) was rightfully in the Receiving Party's possession before receipt from the Disclosing Party; (c) is rightfully obtained by the Receiving Party from a third party without restriction; (d) is independently developed by the Receiving Party without use of or reference to the Disclosing Party's Confidential Information; or (e) is disclosed with the prior written consent of the Disclosing Party.</p>
              <p><strong>14.5 Duration:</strong> The confidentiality obligations set forth in this Section 14 shall survive the termination of these Terms and the applicable engagement and shall continue for a period of five (5) years from the date of disclosure, or indefinitely for trade secrets and source code.</p>
              <p><strong>14.6 Return of Confidential Information:</strong> Upon the termination of the engagement or upon the Disclosing Party's request, the Receiving Party shall promptly return or destroy all Confidential Information of the Disclosing Party, including all copies and extracts thereof, and shall certify in writing that such return or destruction has been completed. The Receiving Party may retain one archival copy for legal compliance purposes, subject to continued confidentiality obligations.</p>
              <p><strong>14.7 Breach Notification:</strong> The Receiving Party shall promptly notify the Disclosing Party upon discovering any unauthorized disclosure, access, or use of the Disclosing Party's Confidential Information and shall take all reasonable steps to mitigate the harm and prevent further unauthorized disclosures.</p>
              <p><strong>14.8 Injunctive Relief:</strong> The parties acknowledge that a breach of confidentiality obligations may cause irreparable harm for which monetary damages would be inadequate. Accordingly, the Disclosing Party shall be entitled to seek injunctive relief or specific performance without the requirement of posting a bond or proving actual damages, in addition to any other remedies available at law or equity.</p>
              <p><strong>14.9 NDA Execution:</strong> Either party may request the execution of a separate Non-Disclosure Agreement (NDA) for specific engagements. If a separate NDA is executed, its terms shall govern the confidentiality obligations for that engagement, provided that any terms not addressed in the NDA shall be governed by this Section 14.</p>

              <h2 id="licensing">15. Software Licensing & Usage Rights</h2>
              <p><strong>15.1 License Grant for Custom Software:</strong> Upon full payment of all applicable Fees, and subject to the Client's compliance with these Terms, Vian Software Solutions grants the Client a non-exclusive, non-transferable, perpetual license to use the Work Product for its internal business purposes, subject to the limitations set forth in this Section 15.</p>
              <p><strong>15.2 License for Digital Products:</strong> For Digital Products not subject to a customization agreement, Vian Software Solutions grants the Client a non-exclusive, non-transferable, revocable license to use the Digital Product in accordance with the applicable license terms. Unless otherwise specified, Digital Products may not be resold, sublicensed, or distributed to third parties.</p>
              <p><strong>15.3 Usage Restrictions:</strong> The Client shall not, and shall not permit any third party to: (a) copy, modify, distribute, sell, lease, or sublicense the Software except as expressly permitted; (b) reverse engineer, decompile, or disassemble the Software; (c) remove or alter any copyright, trademark, or proprietary notices; (d) use the Software for any unlawful or prohibited purpose; (e) exceed any usage limits or restrictions specified in the applicable agreement; or (f) use the Software to develop a competing product or service.</p>
              <p><strong>15.4 SaaS and Subscription Licensing:</strong> For SaaS platforms and subscription-based services, the Client's right to use the platform is contingent upon timely payment of subscription Fees. Vian Software Solutions reserves the right to modify, suspend, or discontinue the SaaS platform upon 30 days' notice, with a pro-rata refund of prepaid Fees.</p>
              <p><strong>15.5 Trial and Evaluation Licenses:</strong> Software or platforms provided for trial or evaluation purposes are provided "as-is" without any warranty, and the license terminates automatically at the end of the trial period. Vian Software Solutions may revoke trial access at any time without notice.</p>
              <p><strong>15.6 License Audit:</strong> Vian Software Solutions reserves the right to audit the Client's use of the Software to ensure compliance with these Terms. Such audits shall be conducted upon reasonable notice and during business hours. If an audit reveals non-compliance, the Client shall promptly remedy the non-compliance and pay any additional licensing Fees due.</p>

              <h2 id="third-party">16. Third-Party Services & Dependencies</h2>
              <p><strong>16.1 Third-Party Services:</strong> The Services or Deliverables may incorporate, integrate with, or depend upon third-party services, platforms, APIs, hosting providers, payment gateways, or other external systems ("Third-Party Services"). Vian Software Solutions does not control, endorse, or assume responsibility for any Third-Party Services.</p>
              <p><strong>16.2 Client Responsibility:</strong> The Client is responsible for: (a) obtaining and maintaining any necessary accounts, subscriptions, or licenses for Third-Party Services; (b) paying all Fees associated with Third-Party Services; (c) complying with the terms of service of Third-Party Services; and (d) ensuring that the Third-Party Services are compatible with the Deliverables.</p>
              <p><strong>16.3 No Warranty for Third-Party Services:</strong> Vian Software Solutions makes no warranty, express or implied, with respect to any Third-Party Services, including their availability, performance, security, or fitness for a particular purpose. Any issues arising from Third-Party Services shall be addressed directly between the Client and the third-party provider.</p>
              <p><strong>16.4 Changes to Third-Party Services:</strong> If a Third-Party Service changes its APIs, terms, pricing, or discontinues its service, Vian Software Solutions shall use reasonable efforts to adapt the Deliverables to accommodate such changes, but such efforts may result in additional Fees and timeline adjustments.</p>
              <p><strong>16.5 Open Source Dependencies:</strong> The Work Product may include open-source software components. Vian Software Solutions shall comply with applicable open-source license requirements and shall, upon request, provide the Client with a list of open-source components used in the Deliverables.</p>

              <h2 id="support">17. Support & Maintenance Terms</h2>
              <p><strong>17.1 Warranty Period:</strong> Vian Software Solutions warrants that for a period of 30 days from the date of final acceptance (the "Warranty Period"), the Work Product shall substantially conform to the specifications set forth in the applicable SOW or Quotation. During the Warranty Period, Vian Software Solutions shall, at its own expense, correct any material defects or non-conformities reported by the Client.</p>
              <p><strong>17.2 Warranty Exclusions:</strong> The warranty in Section 17.1 does not apply to: (a) issues caused by modifications made by the Client or third parties; (b) issues arising from the Client's failure to follow instructions or use the Work Product as intended; (c) issues caused by Third-Party Services or dependencies; (d) issues arising from the Client's hardware, software, or network environment; (e) cosmetic or non-material issues that do not affect functionality; or (f) issues caused by Force Majeure events.</p>
              <p><strong>17.3 Support Services:</strong> After the Warranty Period, the Client may purchase ongoing support and maintenance services under a separate Support Agreement. Support services may include: bug fixes, minor updates, security patches, uptime monitoring, and technical support.</p>
              <p><strong>17.4 Support Exclusions:</strong> Unless expressly agreed in a Support Agreement, support services do not include: (a) development of new features or functionality; (b) major version upgrades; (c) integration with new Third-Party Services; (d) content updates; (e) training; (f) support for modified or customized versions of the Work Product; or (g) support for issues caused by the Client's negligence, misuse, or unauthorized modifications.</p>
              <p><strong>17.5 Response Times:</strong> Support response times shall be as specified in the applicable Support Agreement. In the absence of a Support Agreement, Vian Software Solutions shall use reasonable efforts to respond to support requests but shall have no obligation to provide support.</p>
              <p><strong>17.6 End of Life:</strong> Vian Software Solutions reserves the right to discontinue support for any software or platform upon 90 days' written notice to the Client. In such event, Vian Software Solutions shall provide reasonable assistance to migrate the Client's data to an alternative solution.</p>

              <h2 id="account">18. Account Registration & Security</h2>
              <p><strong>18.1 Account Creation:</strong> Certain Services may require the Client to create an account. The Client agrees to: (a) provide accurate, current, and complete registration information; (b) maintain and promptly update account information; (c) maintain the confidentiality of login credentials; (d) notify Vian Software Solutions immediately of any unauthorized use of the account; and (e) be responsible for all activities that occur under the account.</p>
              <p><strong>18.2 Account Security:</strong> The Client is responsible for implementing and maintaining appropriate security measures to protect their account, including using strong passwords, enabling two-factor authentication where available, and restricting access to authorized personnel.</p>
              <p><strong>18.3 Shared Accounts:</strong> Account sharing is prohibited unless expressly permitted. The Client shall not share login credentials with unauthorized individuals. Each user should have a unique account.</p>
              <p><strong>18.4 Account Suspension:</strong> Vian Software Solutions reserves the right to suspend or terminate accounts that: (a) violate these Terms; (b) engage in suspicious or fraudulent activity; (c) pose a security risk to our systems or other users; or (d) are inactive for 12 months or more.</p>

              <h2 id="aup">19. Acceptable Use Policy</h2>
              <p>The Client agrees not to use the Website, Services, or any Deliverables for any purpose that is unlawful, prohibited by these Terms, or harmful to Vian Software Solutions or third parties. Prohibited activities include, but are not limited to:</p>
              <p><strong>19.1 Illegal Activities:</strong> Engaging in any activity that violates any applicable law, regulation, or ordinance, including but not limited to intellectual property infringement, data privacy violations, fraud, money laundering, and cybercrime.</p>
              <p><strong>19.2 Harmful Content:</strong> Transmitting, storing, or distributing malware, viruses, ransomware, trojans, worms, or any other harmful code or content.</p>
              <p><strong>19.3 Unauthorized Access:</strong> Attempting to gain unauthorized access to our systems, networks, or data, or to the systems or data of third parties.</p>
              <p><strong>19.4 Abuse of Resources:</strong> Using our Services or Deliverables in a manner that imposes an unreasonable or disproportionate load on our infrastructure, including denial-of-service attacks, spamming, or resource exhaustion.</p>
              <p><strong>19.5 Misrepresentation:</strong> Impersonating any person or entity, falsely representing affiliation with any person or entity, or providing false or misleading information.</p>
              <p><strong>19.6 Data Scraping:</strong> Using automated tools, bots, or scrapers to extract data from our Website or Services without our prior written consent.</p>
              <p><strong>19.7 Competitive Use:</strong> Using the Deliverables or Services to develop a competing product or service, or to reverse engineer our proprietary methodologies.</p>
              <p><strong>19.8 Violation of Third-Party Rights:</strong> Using the Services or Deliverables in a manner that infringes the intellectual property rights, privacy rights, or other legal rights of any third party.</p>
              <p><strong>19.9 Reporting Violations:</strong> If you become aware of any violation of this Acceptable Use Policy, you shall immediately notify Vian Software Solutions at support@viannn.online.</p>

              <h2 id="termination">20. Termination & Suspension</h2>
              <p><strong>20.1 Termination by Convenience:</strong> Either party may terminate an engagement for convenience by providing 30 days' written notice to the other party. In the event of termination for convenience by the Client, the Client shall pay all Fees due for work performed up to the effective date of termination, including any non-cancellable commitments made by Vian Software Solutions.</p>
              <p><strong>20.2 Termination for Cause:</strong> Either party may terminate an engagement immediately upon written notice if the other party: (a) materially breaches these Terms and fails to cure such breach within 15 days of receiving written notice; (b) becomes insolvent, files for bankruptcy, or is the subject of bankruptcy proceedings; (c) ceases operations or is unable to perform its obligations; or (d) engages in fraudulent or illegal conduct related to the engagement.</p>
              <p><strong>20.3 Suspension:</strong> Vian Software Solutions may suspend Services immediately upon written notice if: (a) the Client fails to make any payment when due; (b) the Client breaches any provision of these Terms; (c) the Client's use of the Services poses a security risk or legal liability; or (d) as required by applicable law. Suspension shall not relieve the Client of its payment obligations.</p>
              <p><strong>20.4 Effect of Termination:</strong> Upon termination of an engagement: (a) the Client shall pay all Fees due for work performed up to the date of termination, including any non-cancellable commitments; (b) each party shall return or destroy the other party's Confidential Information; (c) Vian Software Solutions shall deliver all Work Product completed up to the date of termination, subject to payment of applicable Fees; (d) any licenses granted to the Client shall terminate, subject to Section 20.6; and (e) the provisions of these Terms that by their nature should survive termination shall survive, including but not limited to Sections 13 (IP), 14 (Confidentiality), 22 (Disclaimer), 23 (Limitation of Liability), 24 (Indemnification), and 26 (Dispute Resolution).</p>
              <p><strong>20.5 Termination of Digital Product Licenses:</strong> Vian Software Solutions reserves the right to terminate licenses for Digital Products if the Client breaches the license terms, with or without notice.</p>
              <p><strong>20.6 Survival:</strong> The rights and obligations of the parties under the following sections shall survive any termination or expiration of these Terms: Sections 13 (Intellectual Property Rights), 14 (Confidentiality), 22 (Disclaimer of Warranties), 23 (Limitation of Liability), 24 (Indemnification), 25 (Governing Law), 26 (Dispute Resolution), 28 (Entire Agreement), 29 (Severability), 30 (Waiver), 31 (Assignment), 32 (Notices), and 33 (Contact Information).</p>

              <h2 id="force-majeure">21. Force Majeure</h2>
              <p>Neither party shall be liable for any failure or delay in performing its obligations under these Terms (other than payment obligations) if such failure or delay is caused by a Force Majeure Event. The affected party shall: (a) promptly notify the other party of the Force Majeure Event and its anticipated duration; (b) use reasonable efforts to mitigate the impact of the Force Majeure Event; and (c) resume performance of its obligations as soon as reasonably practicable. If a Force Majeure Event continues for more than 30 consecutive days, either party may terminate the affected engagement without liability, and the Client shall pay for all work performed up to the date of the Force Majeure Event.</p>

              <h2 id="disclaimer">22. Disclaimer of Warranties</h2>
              <p><strong>22.1 Services Provided "As Is":</strong> Except as expressly provided in these Terms or in the applicable SOW, the Services, Work Product, Deliverables, Digital Products, and all other materials provided by Vian Software Solutions are provided "AS IS" and "AS AVAILABLE" without any warranties, express or implied.</p>
              <p><strong>22.2 Exclusion of Implied Warranties:</strong> To the maximum extent permitted by applicable law, Vian Software Solutions expressly disclaims all implied warranties, including but not limited to: (a) the implied warranties of merchantability, fitness for a particular purpose, and non-infringement; (b) the implied warranty of satisfactory quality; (c) the implied warranty arising from course of dealing, course of performance, or usage of trade; and (d) any warranty that the Services or Deliverables will be error-free, uninterrupted, secure, or operate without interruption.</p>
              <p><strong>22.3 No Guarantee of Specific Results:</strong> Vian Software Solutions does not guarantee that: (a) the Services or Deliverables will meet the Client's specific business objectives, revenue targets, or performance goals; (b) the operation of the Deliverables will be error-free or uninterrupted; (c) all defects will be corrected; or (d) the Deliverables will be compatible with any specific hardware, software, or environment not expressly specified in the SOW.</p>
              <p><strong>22.4 Website Disclaimer:</strong> The information, content, and materials on Vian Software Solutions' website are provided for general informational purposes only and do not constitute professional advice. Vian Software Solutions makes no representations or warranties regarding the accuracy, completeness, or reliability of any information on the website.</p>
              <p><strong>22.5 Beta and Pre-Release:</strong> Any Services, software, or features provided as "beta," "pre-release," "trial," or "evaluation" versions are provided "AS IS" without any warranty whatsoever, and Vian Software Solutions may discontinue them at any time without notice.</p>

              <h2 id="liability">23. Limitation of Liability</h2>
              <p><strong>23.1 No Consequential Damages:</strong> To the maximum extent permitted by applicable law, in no event shall Vian Software Solutions be liable to the Client or any third party for any indirect, incidental, special, exemplary, punitive, or consequential damages arising out of or in connection with these Terms, the Services, or the Deliverables, whether based on contract, tort (including negligence), strict liability, or any other legal theory, even if Vian Software Solutions has been advised of the possibility of such damages. Consequential damages expressly excluded include but are not limited to: loss of revenue, loss of profits, loss of business, loss of goodwill, loss of data, loss of use, cost of substitute services, business interruption, and loss of anticipated savings.</p>
              <p><strong>23.2 Aggregated Funds and Liability Cap:</strong> The total funds and financial exposure of Vian Software Solutions, in relation to any engagement, shall be limited to and construed as the aggregate sum of fees payable under the specific Statement of Work or quotation giving rise to the claim. Under no circumstances shall Vian Software Solutions' aggregate liability exceed the total amount paid or payable by the Client under the specific project engagement from which the claim arises.</p>
              <p><strong>23.3 Cap on Damages:</strong> To the maximum extent permitted by applicable law, the total aggregate liability of Vian Software Solutions, its owners, employees, contractors, and agents, arising out of or in connection with these Terms or any engagement, whether in contract, tort (including negligence), strict liability, or any other legal theory, shall not exceed the total amount paid by the Client to Vian Software Solutions under the specific engagement giving rise to the claim during the 12-month period immediately preceding the event giving rise to the claim.</p>
              <p><strong>23.4 Basis of the Bargain:</strong> The parties acknowledge and agree that the limitations of liability set forth in this Section 23 are fundamental to the bargain and reflect a fair allocation of risk between the parties. The Fees charged reflect these limitations, and Vian Software Solutions would not enter into any engagement without these limitations.</p>
              <p><strong>23.5 Exceptions to Limitations:</strong> Nothing in this Section 23 shall limit or exclude liability for: (a) death or personal injury caused by negligence; (b) fraud or fraudulent misrepresentation; (c) willful misconduct or gross negligence; (d) breach of confidentiality obligations under Section 14; (e) infringement of Intellectual Property Rights; or (f) any liability that cannot be excluded or limited under applicable law.</p>
              <p><strong>23.6 Client's Liability:</strong> Nothing in these Terms shall limit the Client's liability for: (a) payment obligations; (b) breach of confidentiality or IP obligations; (c) infringement of third-party rights; or (d) any liability that cannot be limited under applicable law.</p>
              <p><strong>23.7 Time Limitation:</strong> No action arising out of or in connection with these Terms or any engagement may be brought by either party more than two (2) years after the cause of action accrues, except for claims of breach of confidentiality or Intellectual Property Rights, which may be brought within the applicable statutory limitation period.</p>

              <h2 id="indemnification">24. Indemnification</h2>
              <p><strong>24.1 Indemnification by Client:</strong> The Client agrees to defend, indemnify, and hold harmless Vian Software Solutions, its owners, employees, contractors, agents, and affiliates from and against any and all claims, demands, actions, liabilities, damages, losses, costs, and expenses (including reasonable legal fees) arising out of or in connection with: (a) the Client's use of the Services or Deliverables in violation of these Terms; (b) the Client's breach of any representation, warranty, or obligation under these Terms; (c) the Client's violation of any applicable law, regulation, or third-party right; (d) any content, data, or materials provided by the Client; (e) any claim that the Client's use of the Deliverables infringes any third-party Intellectual Property Rights, unless such infringement is caused by the Work Product as delivered; and (f) any dispute between the Client and its customers, users, or other third parties arising from the use of the Deliverables.</p>
              <p><strong>24.2 Indemnification by Vian Software Solutions:</strong> Vian Software Solutions agrees to defend, indemnify, and hold harmless the Client from and against any claim that the Work Product (excluding third-party and open-source components) as delivered infringes any valid Intellectual Property Right of a third party, provided that: (a) the Client promptly notifies Vian Software Solutions in writing of the claim; (b) Vian Software Solutions has sole control over the defense and settlement of the claim; and (c) the Client provides reasonable cooperation in the defense. If the Work Product is found to infringe, Vian Software Solutions may, at its option and expense: (i) procure the right for the Client to continue using the Work Product; (ii) modify the Work Product to make it non-infringing; or (iii) replace the infringing component with a non-infringing equivalent. This Section 24.2 states Vian Software Solutions' entire liability and the Client's exclusive remedy for infringement claims.</p>
              <p><strong>24.3 Indemnification Procedure:</strong> The indemnified party shall: (a) provide prompt written notice of any claim to the indemnifying party; (b) permit the indemnifying party to assume sole control of the defense and settlement; and (c) provide reasonable assistance in the defense at the indemnifying party's reasonable expense. The indemnifying party shall not settle any claim without the indemnified party's prior written consent if such settlement requires an admission of fault or imposes any obligation on the indemnified party.</p>

              <h2 id="governing-law">25. Governing Law</h2>
              <p>These Terms and all engagements between the Client and Vian Software Solutions shall be governed by and construed in accordance with the laws of the Republic of India. The application of the United Nations Convention on Contracts for the International Sale of Goods (CISG) is expressly excluded. All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts situated in Mumbai, Maharashtra, India. The parties irrevocably submit to the personal jurisdiction of such courts for the purpose of any such dispute.</p>

              <h2 id="dispute-resolution">26. Dispute Resolution & Arbitration</h2>
              <p><strong>26.1 Amicable Resolution:</strong> In the event of any dispute, controversy, or claim arising out of or relating to these Terms or any engagement, the parties shall first attempt to resolve the dispute through good-faith negotiations. The complaining party shall provide written notice of the dispute to the other party, and senior representatives of both parties shall meet within 15 days to attempt to resolve the matter.</p>
              <p><strong>26.2 Mediation:</strong> If the dispute cannot be resolved through negotiations within 30 days, the parties agree to attempt to settle the dispute through mediation administered by a mutually agreed mediator. The mediation shall be conducted in Mumbai, Maharashtra, India, or virtually if agreed by both parties. The cost of mediation shall be shared equally between the parties.</p>
              <p><strong>26.3 Arbitration:</strong> If the dispute cannot be resolved through mediation within 45 days of the commencement of mediation, the dispute shall be finally settled by binding arbitration in accordance with the Arbitration and Conciliation Act, 1996 of India. The arbitration shall be conducted by a sole arbitrator mutually appointed by the parties, or if the parties cannot agree on a sole arbitrator within 30 days, by three arbitrators, one appointed by each party, and the third appointed by the two party-appointed arbitrators.</p>
              <p><strong>26.4 Arbitration Rules:</strong> The arbitration shall be conducted in accordance with the rules of the Mumbai Centre for International Arbitration (MCIA) or such other arbitration institution as the parties may agree. The seat and venue of the arbitration shall be Mumbai, Maharashtra, India. The language of the arbitration shall be English.</p>
              <p><strong>26.5 Arbitration Award:</strong> The arbitral award shall be final and binding on both parties, and judgment on the award may be entered in any court having jurisdiction. The costs of the arbitration (including legal fees) shall be borne by the parties as determined by the arbitral tribunal.</p>
              <p><strong>26.6 Injunctive Relief:</strong> Notwithstanding the foregoing, either party may seek interim injunctive relief from a court of competent jurisdiction in Mumbai, Maharashtra, India, to protect its Confidential Information, Intellectual Property Rights, or to enforce payment obligations, without waiving the right to arbitrate the underlying dispute.</p>
              <p><strong>26.7 Small Claims:</strong> Notwithstanding the foregoing, disputes with a value of less than INR 50,000 may be resolved through summary proceedings in the courts of Mumbai, Maharashtra, India, at the option of either party.</p>

              <h2 id="modifications">27. Modifications to Terms</h2>
              <p>Vian Software Solutions reserves the right to modify, update, or replace these Terms at any time at its sole discretion. Material changes will be effective 15 days after posting the revised Terms on our website, with notice provided via email or prominent website notice. Non-material changes are effective immediately upon posting. Your continued use of our Services or Website after the effective date of any changes constitutes your acceptance of the revised Terms. If you do not agree to the revised Terms, you must discontinue use of our Services and Website. For ongoing engagements, changes to Terms shall not apply retroactively to accepted Quotations or SOWs unless mutually agreed.</p>

              <h2 id="entire-agreement">28. Entire Agreement</h2>
              <p>These Terms, together with the applicable Quotation or Statement of Work, the <a href="/legal/privacy-policy">Privacy Policy</a>, and the <a href="/legal/refund-policy">Refund & Cancellation Policy</a>, constitute the entire agreement between the parties with respect to the subject matter hereof and supersede all prior and contemporaneous agreements, understandings, negotiations, and communications, whether written or oral. The parties expressly reject the application of any standard terms and conditions of the Client, whether printed on a purchase order, invoice, or other document, unless expressly accepted in writing by Vian Software Solutions. No terms or conditions of the Client shall be binding on Vian Software Solutions unless expressly agreed in writing.</p>

              <h2 id="severability">29. Severability</h2>
              <p>If any provision of these Terms is found to be invalid, illegal, or unenforceable by a court or tribunal of competent jurisdiction, such provision shall be modified to the minimum extent necessary to make it enforceable, or if it cannot be modified, it shall be severed from these Terms. The validity and enforceability of the remaining provisions shall not be affected. The parties shall negotiate in good faith to replace any severed provision with a valid provision that most closely approximates the original intent of the parties.</p>

              <h2 id="waiver">30. Waiver</h2>
              <p>No failure or delay by either party in exercising any right, power, or remedy under these Terms shall operate as a waiver thereof, nor shall any single or partial exercise of any right, power, or remedy preclude any other or further exercise thereof or the exercise of any other right, power, or remedy. No waiver shall be effective unless made in writing and signed by the waiving party. A waiver of any breach or default shall not constitute a waiver of any subsequent breach or default.</p>

              <h2 id="assignment">31. Assignment</h2>
              <p>The Client may not assign, transfer, delegate, or sublicense any of its rights or obligations under these Terms without the prior written consent of Vian Software Solutions. Any attempted assignment without such consent shall be void. Vian Software Solutions may assign, transfer, or delegate its rights and obligations under these Terms: (a) to an affiliate; (b) in connection with a merger, acquisition, reorganization, or sale of all or substantially all of its assets; or (c) with the Client's consent, which shall not be unreasonably withheld. Subject to the foregoing, these Terms shall be binding upon and inure to the benefit of the parties and their respective successors and permitted assigns.</p>

              <h2 id="notices">32. Notices</h2>
              <p>All formal notices, demands, and other communications required or permitted under these Terms shall be in writing and shall be deemed duly given when: (a) delivered personally; (b) sent by registered or certified mail, return receipt requested, postage prepaid; (c) sent by a reputable overnight courier service; or (d) sent by email to the designated contact addresses specified below, with confirmation of receipt. Notices to Vian Software Solutions shall be addressed to: Vian Software Solutions, Attn: Viren Pandey, Proprietor, Email: support@viannn.online. Notices to the Client shall be addressed to the contact information provided by the Client in the applicable engagement documentation. Either party may update its notice address by providing written notice to the other party in accordance with this Section.</p>

              <h2 id="contact">33. Contact Information</h2>
              <p>For questions, concerns, or inquiries regarding these Terms, please contact us at:</p>
              <p><strong>Vian Software Solutions</strong><br />Sole Proprietorship of Viren Pandey<br />Mumbai, Maharashtra, India<br />Email: support@viannn.online<br />Phone: +91 9598443203</p>
              <p>For project inquiries, quotations, and service requests, please reach out via email with a description of your requirements. We aim to respond to all inquiries within 24 business hours.</p>
              <p>For legal notices and formal communications, please use the notice address specified in Section 32 of these Terms.</p>
              <p>For dispute-related communications, please refer to the Dispute Resolution process outlined in Section 26 of these Terms.</p>
              <div className="legal-note"><strong>Last updated:</strong> June 25, 2026</div>
            </div>
          </div>
        </div>
      </section>
    </>
  )
}
